language: python

python:
  - "2.7"
  - "3.6"

before_install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - else
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hasr -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n testing python=$TRAVIS_PYTHON_VERSION

install:
  - conda activate testing
  - conda install -q coverage jinja2
  - python setup.py install

script:
  - python -m coverage erase
  - python -m coverage run setup.py
  - python -m coverage report
